### ISSUE TITLE
problem when numa.node_to_cpus() is called twice

### ISSUE THREAD

**Issue by minkang2014** [smira/py-numa#4]
```

$ python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numa
>>> numa.node_to_cpus(0)
set([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46])
>>> numa.node_to_cpus(0)
map size mismatch; abort
: Success
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numa.pyx", line 69, in numa.node_to_cpus (numa.c:1466)
RuntimeError: 0
```

**Comment by smira** [comment]
I'm not actively using this library, but looks like it might be providing buffer which is too small. It's hardcoded for 8 bytes, so 64 bits only.

**Comment by eckman914** [comment]
I'm seeing the same issue.  Is there a fix planned?
exmaple of the problem.
-----------------------------------------------------
[root@d51bp-21 Launchy]# python3
Python 3.8.2 (default, Jul 21 2020, 14:12:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numa
>>> cores = numa.node_to_cpus(1)
>>> cores = numa.node_to_cpus(1)
map size mismatch; abort
: Success
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numa.pyx", line 71, in numa.node_to_cpus
RuntimeError: 1
--------------------------------------------------

**Comment by eckman914** [comment]
I'm seeing the same issue.  Is there a fix planned?
Here's an example of the problem.

[root@d51bp-21 Launchy]# python3
Python 3.8.2 (default, Jul 21 2020, 14:12:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numa
>>> cores = numa.node_to_cpus(1)
>>> cores = numa.node_to_cpus(1)
map size mismatch; abort
: Success
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numa.pyx", line 71, in numa.node_to_cpus
RuntimeError: 1
